[UPDATE] for check the coding style

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -38,36 +38,21 @@ jobs:
         with:
           repository: ''
 
-      - name: Run coding-style
-        run: check.sh . /tmp
+      - name: Run coding-style checker script
+        run: check.sh $(pwd) $(pwd)
 
-      - name: Create annotation for coding-style errors
+      - name: Display coding style errors as annotations if any
+        id: annotations
+        if: failure()
         run: |
-          input=/tmp/coding-style-reports.log
-          if [ !-f "$input"] || [ !-s "$input"]; then
-            echo "Error: $input file does not exist or is empty"
-            exit 1
-          fi
-          while IFS= read -r -a line; do
-            fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
-          if [ ${#fields[@]} -ne 4 ]; then
-          echo "Error: Unexpected number of fields in line: $line"
-          continue
-          fi
-          if [ -z "${fields[0]}" ] || [ -z "${fields[1]}" ] || [ -z "${fields[2]}" ] || [ -z "${fields[3]}" ]; then
-          echo "Error: Missing data in fields array: ${fields[@]}"
-          continue
-          fi
-          echo "::error title=${fields[2]} coding style error, file=${fields[0]}, line=${fields[1]}::${fields[3]}"
-          done < $input
+          cat coding-style-reports.log | while read line ; do
+            echo "$line" >> error.log;
+          done;
+          echo "::error file=error.log::$(cat error.log)"
 
-      - name: Report banana result
-        run: |
-          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
-          NB_ERROR=$((NB_ERROR-1))
-          if [ $NB_ERROR -gt 0 ]; then
-            exit 1
-          fi
+      - name: Fail the job if there are any coding style errors.
+        if: failure()
+        run: exit 1
 
   check_program_compilation:
     runs-on: ubuntu-latest
