[ADD] fix the workflow for unit_test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -24,9 +24,21 @@ jobs:
       - name: Create annotation for coding-style errors
         run: |
           input=/tmp/coding-style-reports.log
+          if [ !-f "$input"] || [ !-s "$input"]; then
+            echo "Error: $input file does not exist or is empty"
+            exit 1
+          fi
           while IFS= read -r -a line; do
             fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
-            echo "::error title=${fields[2]} coding style error, file=${fields[0]}, line=${fields[1]}::${fields[3]}"
+          if [ ${#fields[@]} -ne 4 ]; then
+          echo "Error: Unexpected number of fields in line: $line"
+          continue
+          fi
+          if [ -z "${fields[0]}" ] || [ -z "${fields[1]}" ] || [ -z "${fields[2]}" ] || [ -z "${fields[3]}" ]; then
+          echo "Error: Missing data in fields array: ${fields[@]}"
+          continue
+          fi
+          echo "::error title=${fields[2]} coding style error, file=${fields[0]}, line=${fields[1]}::${fields[3]}"
           done < $input
 
       - name: Report banana result
@@ -77,7 +89,7 @@ jobs:
        repository: ''
 
     - name: Compile tests binaries
-      run: make tests_run
+      run: make unit_tests
 
   push_to_mirror:
     runs-on: ubuntu-latest
