[UPDATE] fail coding style for test the worflow

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -46,9 +46,14 @@ jobs:
         run: |
           NB_ERRORS=$(cat coding-style-reports.log | wc -l)
           if [ $NB_ERRORS -ge 1 ]; then
-            ERROR=$(cat coding-style-reports.log)
-            echo "::error title=$NB_ERRORS coding style errors found::$ERROR"
-            exit 1
+            while IFS=read -r line
+            do
+              FILE=$(echo $line | cut -d ':' -f1)
+              LINE=$(echo $line | cut -d ':' -f2)
+              ERROR=$(echo $line | cut -d ':' -f3-)
+              echo "::error file=$FILE,line=$LINE,title=$NB_ERRORS coding style errors found::$ERROR"
+                done < coding-style-reports.log
+              exit 1
           fi
           exit 0
 
